### ISSUE TITLE
Alternative: Windows Group Policy/Registry tweaks (block the automatic install of USB devices)

### ISSUE THREAD

**Issue by ZiroKyl** [anatolymik/samples#1]
- [EN] [Locking down Windows against Malicious USB devices](http://www.irongeek.com/i.php?page=security%2Fplug-and-prey-malicious-usb-devices#3.1_Locking_down_Windows_Vista_and_Windows_7_against_Malicious_USB_devices)
- [RU] [Блокировка USB-накопителей при помощи возможностей групповой политики](http://gpo-planet.com/?p=3218)

**Comment by anatolymik** [comment]
First of all, from your article, devices are blocked by preventing installing of their drivers. If drivers are already installed they wouldn't be blocked. It's simplier to user to install driver which will block devices without their drivers removing.
